IF DB_ID('Bowling_Tournament') IS NULL
    CREATE DATABASE Bowling_Tournament;

/*
SELECT *
FROM EMPLOYEE
FULL OUTER JOIN DEPARTMENT
*/

USE Bowling_Tournament;

USE MASTER;

IF OBJECT_ID('TOURNAMENTS', 'B') IS NULL
    CREATE TABLE TOURNAMENTS(
        TOURNEY_ID INT PRIMARY KEY,
        TOURNEY_DATE DATE,
        TOURNEY_LOCATION VARCHAR(50)
    );


IF OBJECT_ID('TEAMS', 'B') IS NULL
    CREATE TABLE TEAMS(
        TEAM_ID INT PRIMARY KEY,
        TEAM_NAME VARCHAR(30),
        TOURNEY_LOCATION VARCHAR(50)
    );

EXEC SP_RENAME 'DBO.SOMETHINGS', 'TOURNAMENTS'

IF OBJECT_ID('TOURNEY_MATCHES', 'B') IS NULL 
    CREATE TABLE TOURNEY_MATCHES(
        MATCH_ID INT PRIMARY KEY,
        TOURNEY_ID INT,
        LANES INT,
        ODD_LANE_TEAM_ID INT,
        EVEN_LANE_TEAM_ID INT
    )

IF OBJECT_ID('BOWLERS', 'B') IS NULL 
    CREATE TABLE BOWLERS(
        BOWLER_ID INT PRIMARY KEY,
        BOWLER_LAST_NAME VARCHAR(20),
        BOWLER_FIRST_NAME VARCHAR(20),
        BOWLER_MIDDLE_INIT CHAR,
        BOWLER_STREET_ADDRESS VARCHAR(50),
        BOWLER_CITY VARCHAR(15),
        BOWLER_STATE VARCHAR(15),
        BOWLER_ZIP_CODE INT,
        BOWLER_PHONE_NUMBER VARCHAR(20),
        TEAM_ID INT,

        CONSTRAINT TEAM_ID_FK FOREIGN KEY(TEAM_ID) REFERENCES TEAMS(TEAM_ID)
    
    );

ALTER TABLE BOWLERS
ALTER COLUMN BOWLER_ZIP_CODE VARCHAR(10);

IF OBJECT_ID('MATCH_GAMES', 'B') IS NULL
    CREATE TABLE MATCH_GAMES(
        MATCH_ID INT,
        GAME_NUMBER INT,
        WINNING_TEAM_ID INT,

        PRIMARY KEY(MATCH_ID, GAME_NUMBER),
        CONSTRAINT WINNING_TEAM_ID_FK FOREIGN KEY(WINNING_TEAM_ID) REFERENCES TEAMS(TEAM_ID)
    );

IF OBJECT_ID('BOWLER_SCORES', 'B') IS NULL
    CREATE TABLE BOWLER_SCORES(
        MATCH_ID INT,
        GAME_NUMBER INT,
        BOWLER_ID INT,
        HANDICAP_SCORE INT,
        WON_GAME CHAR,

        PRIMARY KEY(MATCH_ID, GAME_NUMBER, BOWLER_ID),
        CONSTRAINT GAMER_MATCHER_FK FOREIGN KEY(MATCH_ID, GAME_NUMBER) REFERENCES MATCH_GAMES(MATCH_ID, GAME_NUMBER),
        CONSTRAINT BOWLER_ID_FK FOREIGN KEY(BOWLER_ID) REFERENCES BOWLERS(BOWLER_ID)
    );

ALTER TABLE TEAMS
DROP COLUMN TOURNEY_LOCATION;

ALTER TABLE TEAMS
ADD CAPTAIN_ID INT REFERENCES BOWLERS(BOWLER_ID)

ALTER TABLE TOURNEY_MATCHES
ADD CONSTRAINT ODD_LANE_TEAM_ID_FK FOREIGN KEY(ODD_LANE_TEAM_ID) REFERENCES TEAMS(TEAM_ID);

ALTER TABLE TOURNEY_MATCHES
ADD CONSTRAINT EVEN_LANE_TEAM_ID_FK FOREIGN KEY(EVEN_LANE_TEAM_ID) REFERENCES TEAMS(TEAM_ID);

ALTER TABLE TOURNEY_MATCHES
ADD CONSTRAINT TOURNEY_ID_FK FOREIGN KEY(TOURNEY_ID) REFERENCES TOURNAMENTS(TOURNEY_ID);

ALTER TABLE BOWLERS
DROP COLUMN BOWLER_TOTAL_PINS, BOWLER_GAMES_BOWLED, BOWLER_CURRENT_AVERAGE, BOWLER_CURRENT_HCP;

ALTER DATABASE Bowling_Tournament MODIFY NAME = [BOWLING_TOURNAMENT];


-- Important before changing
ALTER DATABASE Bowling_Tournament
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;